-- Altera o tipo de dado das colunas de chave primária para BIGINT para corresponder às entidades JPA.
-- Nota: A execução pode falhar se as tabelas já estiverem com BIGINT, mas o Flyway lidará com a transação.

ALTER TABLE TB_MTT_CAMERA ALTER COLUMN id BIGINT;
ALTER TABLE TB_MTT_CIDADE ALTER COLUMN id BIGINT;
ALTER TABLE TB_MTT_ESTADO ALTER COLUMN id BIGINT;
ALTER TABLE TB_MTT_FILIAL ALTER COLUMN id BIGINT;
ALTER TABLE TB_MTT_IOT ALTER COLUMN id BIGINT;
ALTER TABLE TB_MTT_LOGRADOURO ALTER COLUMN id BIGINT;
ALTER TABLE TB_MTT_USUARIO ALTER COLUMN id BIGINT;
ALTER TABLE TB_MTT_VEICULO ALTER COLUMN id BIGINT;
