-- V5: Altera o tipo de dado das colunas de ID para BIGINT, removendo e recriando as restrições necessárias.

-- ETAPA 1: Remover todas as restrições de chave estrangeira que serão recriadas.
ALTER TABLE TB_MTT_CIDADE DROP CONSTRAINT FK_CIDADE_ESTADO;
ALTER TABLE TB_MTT_VEICULO DROP CONSTRAINT FK_VEICULO_USUARIO;
ALTER TABLE TB_MTT_CAMERA DROP CONSTRAINT FK_CAMERA_FILIAL;
ALTER TABLE TB_MTT_IOT DROP CONSTRAINT FK_IOT_VEICULO;
ALTER TABLE TB_MTT_LOGRADOURO DROP CONSTRAINT FK_LOGRADOURO_USUARIO;
ALTER TABLE TB_MTT_LOGRADOURO DROP CONSTRAINT FK_LOGRADOURO_FILIAL;
ALTER TABLE TB_MTT_LOGRADOURO DROP CONSTRAINT FK_LOGRADOURO_CIDADE;

-- ETAPA 2: Remover dinamicamente as restrições de chave primária.
-- O SQL Server gera nomes únicos para PKs, então usamos SQL dinâmico para encontrá-los e removê-los.
DECLARE @sql_pk NVARCHAR(MAX) = N'';
SELECT @sql_pk += N'ALTER TABLE ' + QUOTENAME(OBJECT_SCHEMA_NAME(parent_object_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + ' DROP CONSTRAINT ' + QUOTENAME(name) + ';'
FROM sys.key_constraints
WHERE type = 'PK' AND OBJECT_NAME(parent_object_id) IN (
    'TB_MTT_CAMERA', 'TB_MTT_CIDADE', 'TB_MTT_ESTADO', 'TB_MTT_FILIAL',
    'TB_MTT_IOT', 'TB_MTT_LOGRADOURO', 'TB_MTT_USUARIO', 'TB_MTT_VEICULO'
);
EXEC sp_executesql @sql_pk;

-- ETAPA 3: Agora que as colunas estão livres de restrições, alterar seus tipos.
ALTER TABLE TB_MTT_CAMERA ALTER COLUMN id BIGINT NOT NULL;
ALTER TABLE TB_MTT_CIDADE ALTER COLUMN id BIGINT NOT NULL;
ALTER TABLE TB_MTT_ESTADO ALTER COLUMN id BIGINT NOT NULL;
ALTER TABLE TB_MTT_FILIAL ALTER COLUMN id BIGINT NOT NULL;
ALTER TABLE TB_MTT_IOT ALTER COLUMN id BIGINT NOT NULL;
ALTER TABLE TB_MTT_LOGRADOURO ALTER COLUMN id BIGINT NOT NULL;
ALTER TABLE TB_MTT_USUARIO ALTER COLUMN id BIGINT NOT NULL;
ALTER TABLE TB_MTT_VEICULO ALTER COLUMN id BIGINT NOT NULL;

-- ETAPA 4: Recriar as restrições de chave primária.
ALTER TABLE TB_MTT_CAMERA ADD PRIMARY KEY (id);
ALTER TABLE TB_MTT_CIDADE ADD PRIMARY KEY (id);
ALTER TABLE TB_MTT_ESTADO ADD PRIMARY KEY (id);
ALTER TABLE TB_MTT_FILIAL ADD PRIMARY KEY (id);
ALTER TABLE TB_MTT_IOT ADD PRIMARY KEY (id);
ALTER TABLE TB_MTT_LOGRADOURO ADD PRIMARY KEY (id);
ALTER TABLE TB_MTT_USUARIO ADD PRIMARY KEY (id);
ALTER TABLE TB_MTT_VEICULO ADD PRIMARY KEY (id);

-- ETAPA 5: Recriar todas as restrições de chave estrangeira.
ALTER TABLE TB_MTT_CIDADE ADD CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (tb_mtt_estado_id) REFERENCES TB_MTT_ESTADO (id);
ALTER TABLE TB_MTT_VEICULO ADD CONSTRAINT FK_VEICULO_USUARIO FOREIGN KEY (tb_mtt_usuario_id) REFERENCES TB_MTT_USUARIO (id);
ALTER TABLE TB_MTT_CAMERA ADD CONSTRAINT FK_CAMERA_FILIAL FOREIGN KEY (tb_mtt_filial_id) REFERENCES TB_MTT_FILIAL (id);
ALTER TABLE TB_MTT_IOT ADD CONSTRAINT FK_IOT_VEICULO FOREIGN KEY (tb_mtt_veiculo_id) REFERENCES TB_MTT_VEICULO (id);
ALTER TABLE TB_MTT_LOGRADOURO ADD CONSTRAINT FK_LOGRADOURO_USUARIO FOREIGN KEY (tb_mtt_usuario_id) REFERENCES TB_MTT_USUARIO (id);
ALTER TABLE TB_MTT_LOGRADOURO ADD CONSTRAINT FK_LOGRADOURO_FILIAL FOREIGN KEY (tb_mtt_filial_id) REFERENCES TB_MTT_FILIAL (id);
ALTER TABLE TB_MTT_LOGRADOURO ADD CONSTRAINT FK_LOGRADOURO_CIDADE FOREIGN KEY (tb_mtt_cidade_id) REFERENCES TB_MTT_CIDADE (id);