name: 'Build and deploy JAR app to Azure Web App: app-mottu-rm559105'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: 'challenge java/demo'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-mottu-rm559105'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F51079D7D4C842C39DB5BEC2731ABDAD }}
          package: '${{ github.workspace }}/challenge java/demo/target/*.jar'
